### ISSUE TITLE
Build prototype in InVision

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/connect5#12]
Use the wireframes to build a prototype in InVision. I've already built a rough one within Figma (on the page called "Rough Prototype") which may help in terms of which screens to export and the interactions we want to include.

**Comment by RamyAlshurafa** [comment]
First, Thanks guys for your works in linking the prototype, you really did most of the work!
Here Is the Link for trainer side [prototype](https://www.figma.com/proto/FSYdqP87hx39PwGA74OhkKmu/Connect-5?node-id=90%3A0&scaling=scale-down&redirected=1).
and the participants' side [prototype](https://www.figma.com/proto/FSYdqP87hx39PwGA74OhkKmu/Connect-5?node-id=73%3A4&scaling=scale-down)

**Comment by thejoefriel** [comment]
This looks great! I've moved this to done.
