### ISSUE TITLE
Agree Tech Stack, Packages

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/connect5#14]
We need to agree our provisional tech stack in order that our devops @marwajomaa can start setting up our environment and package.json and we can start coding on Tuesday 13th Nov. 

We now have a clear idea of what the web app is going to be and needs to do. Considering this, can everyone please add comments below with their views on:

- [ ] Tech stack we should use (e.g. React, Express, Postgres)
- [ ] Testing package we want to use (e.g. Jest)
- [ ] Additional packages/middleware we will need (e.g. bodyparser, passport, bcryptjs)
- [ ] Any other bits we need to discuss for set up (e.g. create-react-app)

This does not need to be the complete list, but is enough for us to agree what we provisionally need for the set up.

**Comment by RamyAlshurafa** [comment]
Taking into account the time constraints, I think we haven't time to learn some new tech.
so from my point of view, I think we should work on the mutual tech we all familiar with.
For me, I'm familiar with :

- [ ] Tech stack:
* React
* Express
* Postgres

- [ ] Testing:

* ( Jest or Tape )
* supertest

- [ ] additional packages/middleware 
* JWT
* bcryptjs
* serve-favicon
* body-parser
* env2
* pg

- [ ] Other related
* create-react-app 
* express-generator
* eslint

**Comment by marwajomaa** [comment]
- [ ] **Tech stack:**
* React
* Express
* Postgres
* Testing:
( Jest or Tape )

- [ ] **Additional packages/middleware**
* JWT
* bcryptjs
* serve-favicon
* body-parser
* env2
* pg
* eslint
* nodmon
* react-datepicker
* react-fontawesome
* react-select
* react-moment

- [ ] **additional packages/middleware** 
* react-inputs-validation
* react-validation
* styled-components

**Comment by thejoefriel** [comment]
These are great! I haven't used some of these react packages - are you able to write a quick of one-line explanations please?
