### ISSUE TITLE
Agree build sprint schedule

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/connect5#16]
Hi all, this is what I was thinking for our structure over the next 3 weeks:

> 13th to 19th - Front End Sprint (4.5 days) - potential user testing on afternoon of 19th
> 20th to 27th - Back End Sprint (6 days)
> 28th to 2nd - Debugging and Stretch Goals sprint (3 days)
> 3rd December - Handover

I thought it best to get the front end done first as we can then review the overall style and actions with Elysabeth (and potentially users). 

We would then have more time designated to do the back end, with a final few days left over as contingency for further work and debugging. 

What do people think? @arrested-developer - it'd be great to see if you feel this is sensible too :)

**Comment by arrested-developer** [comment]
I think this looks pretty sensible 👍🏼

Time does feel a bit tight, but I'd be tempted to try and get the front-end sprint done more quickly. If you've got user testing on 19th, you could aim to have front-end fully functional by end of 18th, then you have 1/2 day contingency if needed, which can ideally be used to refactor the frontend and bring everything together.

I think having the last 3 days as contingency time is a great idea - hopefully we'll have thorough tests and no need for extra bug fixing 🐛so you can use this time to refactor.

Out of interest, what time would you draw on if the user testing on 19th shows a lot of changes are needed?

**Comment by RamyAlshurafa** [comment]
that's good :+1:

**Comment by marwajomaa** [comment]
I like that, agree :+1:

**Comment by dupreesi** [comment]
yeah as discussed this afternoon this setup makes a lot of sense and will enable us to work slightly more independently. I also think the timings should work as they are set out by @thejoefriel

**Comment by RamyAlshurafa** [comment]
That's good :+1: 

Did you add this user story to the core sprint?

> Export results (email / pdf download)

If yes, I should add it to user stories.

**Comment by thejoefriel** [comment]
Export will be in core+ so the second sprint. Will add it though so we don't forget! Thanks!
