### ISSUE TITLE
Set up React and Express

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/connect5#19]
- [ ] Create react app
- [ ] Basic express "API"
- [ ] Set up basic test

- Set up the relevant scripts in package.json (e.g. "start", "dev")

Initial thoughts is that this would be using concurrently so we can run both servers at the same time - do you agree @marwajomaa ?

**Comment by marwajomaa** [comment]
@thejoefriel  yeah, I think we need both for client and server sides

**Comment by thejoefriel** [comment]
PS, what is your suggested way of setting these up together in order that we can do testing and ensure codecov? Are you thinking setting it up in two repos within our main repo?

**Comment by marwajomaa** [comment]
> Great. How's it going? Will you be ok to push this up today or still need to work on this tomorrow
I'll try to prepare it by the end of the day, but it's may take me more time to make sure that everything is perfect, so I think tomorrow morning before the stand-up meeting it will ready.

**Comment by marwajomaa** [comment]
> PS, what is your suggested way of setting these up together in order that we can do testing and ensure codecov? Are you thinking setting it up in two repos within our main repo?

Yeah; I'll make a separate folder for each side then I'll join them together using proxy. Is that make sense for you?

**Comment by thejoefriel** [comment]
Hey @marwajomaa you ok to tick the check boxes on this and close this issue please?

That will then move it to done here: https://github.com/techforbetter/connect5/projects/2

**Comment by marwajomaa** [comment]
Ok done
