### ISSUE TITLE
Connect us with users for user testing

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/connect5#2]
@elysabethc5 -  Please can you let us know the email addresses for the users you'd like us to do the user testing with? If you just leave with comments below and ideally when they might be free on Monday 12th Nov that'd be great!

**Comment by thejoefriel** [comment]
Thanks for this update @elysabethc5 ! We'll get in touch with Deb and Richard to set up a time with them.

3 users is fine. Any more is great, but definitely won't need more than 5. Thanks again for sorting!

**Comment by elysabethc5** [comment]
Charlie Paradise <CParadise@swindon.gov.uk> is availble 9-10 if any good

**Comment by elysabethc5** [comment]
Mike Lock <mikel@easthantsmind.org>I can make monday : 10am-11am / 11am-12pm / 3pm-4pm
i will stop now !

**Comment by elysabethc5** [comment]
Mandy Wiltshire <Mwiltshire@solentmind.org.uk>
one more she said availble at 10.30 on monday.

**Comment by elysabethc5** [comment]
Andy Foster <andyf@easthantsmind.org> this person works with mike above and can make 10-12, so you could do the togther. 
that really is it as i am logging off now. 
bye
