### ISSUE TITLE
As a trainer, I want to be able to login into Connect 5 platform.

### ISSUE THREAD

**Issue by RamyAlshurafa** [techforbetter/connect5#27]
Relates #24 
#### Acceptance criteria:
- [x] When I'm on "Login" page, I want to get a form to fill my email and password inputs to fill them and be able to login to the platform.
- [x] When I'm on " Login" page, and I filled wrong details, I want to get a message to notify me that my inputs are wrong.
- [x] When I'm on "Login" page, I want a link to redirect me to "Sign up " page If I didn't register yet.
- [x] When I fill my correct info, I want to be redirected to "Trainer dashboard".
- [x]  When I fill my information, and something wrong happened I need to get "Error" page.

**Comment by thejoefriel** [comment]
*IMPORTANT NOTE*
For this core version, we will not actually check the password, we will only check their email address to find their unique id and route them to the right url to view their information. This allows us to show user flow for user testing purposes. 
Proper authentication and guarded routes is a bonus feature.
