### ISSUE TITLE
Data collection

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/connect5#3]
@elysabethc5 - two questions on the data collection. 

1. Are we able to have a log in to the survey monkey to view the data and see how everything is being collected, or is this access restricted by RSPH?

2. How are they given a Unique ID number? Also, with the current form it says they can enter NA if they don't know. However, if they do this I can't see how you can link them to any previous surveys they have filled in. Do you have any idea on this? Are you currently able to collect all the survey responses that each participant has filled in?

**Comment by elysabethc5** [comment]
i am more than happy for us to use a different platform , anything which makes the data better and more effective is good with me. 
if we could it would be great to give the particpants ID . RSPH says that they havent found a way for the particpnats to remember the ID , so wondered if a way to link with email or region. without the ID we cant relate the pre questionnaire results with the post questionanire results for individuals . does that make sense

**Comment by elysabethc5** [comment]
sorry im still getting the hang of this. and without some identification we cant know what sessions particpnats have done . remember there might be a time laspse between the particpant doing session 1 /2 /3 and we would need to track theat as well as linking up with the pre sessions questionnaire that would only be done once at the beginning of the process. 
this is why the system at the moment is not fit for purpose and is why many of the trainers arent using it .

**Comment by thejoefriel** [comment]
Thanks so much, this is really interesting. I've noticed they don't ask the participant to enter their email address in the survey. Is there a reason we don't do this? We could get them to enter their email address (making it clear that this wouldn't be shared with the trainers and would be privately stored as you currently do when requesting the ID), which they are likely to remember and then we can use this to track the participants, which can then be done automatically without ever sharing their email address with the trainers.

**Comment by thejoefriel** [comment]
Thanks @elysabethc5 . Yeah I feel like the only way of being able to identify the participant is by getting them to enter some form of identification like an email. We could maybe separate out the process, so they first enter their email to confirm they were a participant of that session, and then it takes them to a second screen that will be the response form. This does the same job as currently but maybe will keep identification and feedback separate in the minds of the participants?

**Comment by elysabethc5** [comment]
im happy to to go with that , for the people trained we can make it clear that the email is the way to identify them but seperated from the feedback ie their feedback becomes anonymous
of course for the trianers we need to be able to trace the feedback back to them to monitor their performance
