### ISSUE TITLE
As a trainer I want to view my sessions on a single page, so I can get more info about it.

### ISSUE THREAD

**Issue by RamyAlshurafa** [techforbetter/connect5#30]
## As a trainer I want to view my sessions on a single page, so I can get more info about it.
Relates #24 
 #### Acceptance criteria:
- [ ] When I'm on "Session details" page, I want to get the session details (date, attendance, and session No.).
- [ ] When I'm on "Session details" page, I want to view the session link, so I can copy it and send it to the participants by email.
- [ ] When I'm on "Session details" page, I want a button to take me to the "Session result" page.
- [ ] When I'm on "Session details" page, I want a button to delete that session.
- [ ] When I'm on "session details" page for the first session, I want to get pre-survey link and details.
- [ ] When I'm on "session details" page for the first session, I want to get a button to take me to pre-survey details page.

#### Important functionality:
- [ ] Need to get the information for this session from the Sessions table in the database

**Comment by thejoefriel** [comment]
I have removed the edit function for now and will set this up as a separate issue which we can look at later as this would be a bonus feature.
