### ISSUE TITLE
Create navbar

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/connect5#40]
This is the initial core version, containing the following buttons:

- [x] Sessions
- [x] Add session

**Comment by marwajomaa** [comment]
@thejoefriel  I think you forget to add the other buttons for Home and Results?😊😊

**Comment by thejoefriel** [comment]
Oh actually we decided we didn't need those in there for now as we won't be adding dashboard or results until next week's sprint. 

However, happy for you to put in for now and then they just don't click to anything if you recommend that?
