### ISSUE TITLE
Create normalizing for CSS and create index.css file add the brand colors

### ISSUE THREAD

**Issue by RamyAlshurafa** [techforbetter/connect5#47]
- [ ] Create `normalizer.css` file so it will normalize the default css properties variations on different browsers.
- [ ] Create `index.css` file and put branding colors inside it.

**Comment by thejoefriel** [comment]
Me and @dupreesi will look at setting up Styled Components this morning (issue #52) which will sort out this issue.

**Comment by thejoefriel** [comment]
@RamyAlshurafa @marwajomaa do either of you have any particular design focus or colour preferences you feel we should use?

**Comment by RamyAlshurafa** [comment]
@thejoefriel , actually no.
But we can use some colors from the logo
