### ISSUE TITLE
agree on  file structure [Front-End]

### ISSUE THREAD

**Issue by RamyAlshurafa** [techforbetter/connect5#53]
I have a suggestion for refactoring the file structure for React

Client 
   ├── public
   │    ├── favicon.ico
   │    ├── index.html
   │    └── manifest.json
   ├── src
   │    ├── Component
   │     │        ├── CommonComponents
   │      │         │           ├── <Common 2 Folder>
   │      │         │           ├── <Common 2 Folder>
   │      │         ├── Layouts
   │      │         │          ├── <Layout 1 Folder>
   │      │         │          ├── <Layout 1 Folder>
   │      │         │          ├── <Layout 1 Folder>
   │      │         ├── App..js       
   │      │         └── App.css
   │      ├── index..js       
   │      └── index.css
   ├── package-lock.json
   └── package.json

What do you think?

(Sorry for bad styling, I spent alot of time to fix it but cant figure out whats wrong.)

**Comment by thejoefriel** [comment]
Thanks. So what would go in the CommonComponents then for example?

Also, can you add this to the Project plan and Milestone please.

**Comment by RamyAlshurafa** [comment]
I think any component we will use in many places, in order to prevent work duplication.
I suggest to some components:
  - Navbar (footer)
  - header (in the login, sign up, trainer landing page)
  - question (may need to be reusable, for example, we can pass the question text and the question option as an array in the props)
  - rating bar

**Comment by RamyAlshurafa** [comment]
Should we move the `discuss` issues on the project plan? I thought it's for tasks only?
