### ISSUE TITLE
Use of promises in survey build

### ISSUE THREAD

**Issue by eliascodes** [techforbetter/connect5#65]
Just a little thing I spotted while have a poke through the repo:

https://github.com/techforbetter/connect5/blob/3f1b403bf375b1ac4893460425f1734f052a7211/server/database/surveyBuild.js#L18-L24

`then` takes a function as an argument. On line 21, you are invoking `Model.insertMany`, then passing its return value to `then`. The return value is a promise, not a function.

This means that `deleteMany` and `insertMany` are executed at the _same time_, not sequentially. A simple analogous example is:
```js
Promise.resolve(2).then(1).then(console.log);
```
This logs `2`, not `1`, because non-function values passed to `then` or `catch` [are ignored](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Parameters).

**Comment by RamyAlshurafa** [comment]
Thank you @eliascodes for a good spot. :+1: 
we will fix that :)

**Comment by arrested-developer** [comment]
@RamyAlshurafa has this been resolved?

**Comment by RamyAlshurafa** [comment]
@arrested-developer, Now yes :)
