### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/connect5#8]
Hi @elysabethc5 do you have any brand style guidelines you need us to follow? For example, colours, fonts etc. 

Also, can you please share the Connect 5 logo? And any other images you have that you might like us to look at integrating.

**Comment by elysabethc5** [comment]
![mhep_connect5_logo_hires](https://user-images.githubusercontent.com/44806965/48193659-e25ea400-e342-11e8-941f-41cf296d029c.jpg)
![mhep_connect5_logo_web](https://user-images.githubusercontent.com/44806965/48193660-e25ea400-e342-11e8-8742-6ab60e5db1b7.jpg)
we have some images of characters that we use , shall i sent them

**Comment by elysabethc5** [comment]
these are the illustrations used in the connect 5 
[a166d386-dded-4578-9fb5333d807f691b.pdf](https://github.com/techforbetter/connect5/files/2562462/a166d386-dded-4578-9fb5333d807f691b.pdf)
