### ISSUE TITLE
Initial design meeting

### ISSUE THREAD

**Issue by thejoefriel** [techforbetter/connect5#9]
@elysabethc5 are you free tomorrow say around 12.30 for a quick 20 minute google hangout / skype?

We're keen to show you the black and white wireframes to make sure we're on the right track for you before going into user testing on Monday.

**Comment by elysabethc5** [comment]
yes i am is google hangout easy not sure if i have skype access on work computer

**Comment by thejoefriel** [comment]
Yeah google hangouts would probably be simplest. Do you have a google email address we can invite to the hangout?

**Comment by elysabethc5** [comment]
elyswills@gmail.com
12 noon best for me , as have call 12.45 
cheers

**Comment by thejoefriel** [comment]
Cool, will send you an invite now
